spring.application.name=Reembolsos
server.port=8087

# Conexion MySQL - ajustar password segun tu configuracion local
spring.datasource.url=jdbc:mysql://localhost:3306/reembolsos_db
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
